name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build
        run: wasm-pack build --no-pack --release --out-dir assets --target web --out-name reaction-diffusion --verbose
      - name: Run tests (chrome)
        run: wasm-pack test --chrome --headless --verbose
      - name: Run tests (firefox)
        run: wasm-pack test --firefox --headless --verbose
      - name: Upload built files
        uses: actions/upload-pages-artifact@v3
        with:
          path: assets/

  deploy-github-pages:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build-wasm
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
